# -*- coding: utf-8 -*-
"""Star print using for loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104ZdaDhYUYF6Q7DU_E28gVtKz4CuSxdx
"""

for star in range(0,50):
    for star2 in range(0,star+1):
        print("*",end="")
    print()

for star in range(0,50):
    for star2 in range(50,star,-1):
        print("*",end="")
    print()